### PR TITLE
Fix deprecation warning for set-output

### LINKED ISSUE #2196: Github Action Deprecation notices
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `yarn generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Github Actions are reporting some impending deprecations and changes that could affect functionality.

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: kamilkisiela/graphql-inspector
```

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**To Reproduce** Steps to reproduce the behavior:

Add the action to a workflow
```yml
name: Check GraphQL Schema

on:
  pull_request:
    branches:
      - main

jobs:
  check-graphql-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: 'main:schema.graphql'

```

**Expected behavior**

Deprecations don't show

**Environment:**

- OS: `ubuntu-latest`
- `@graphql-inspector/...`: 3.4.0
- `graphql`: -
- NodeJS: 12

**Additional context**

### PR DESCRIPTION
**Pull request by nathanchapman**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._

## Description

Addresses second half of GitHub Actions Deprecation notices re:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows

This was half-fixed by a renovate update PR (#2301), which upgraded `@actions/core` to `1.10.0`. Now, `action/index.js` just needs to be rebuilt and released.

Fixes #2196

The other deprecation notice is  addressed by #2221 (upgrade from Node12 to Node16)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@graphql-inspector/...`:
- NodeJS:

## Checklist:

- [ ] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by B2o5T** [comment]
plz rebase, also deprecated set output was refactored in this PR https://github.com/kamilkisiela/graphql-inspector/pull/2358

**Comment by nathanchapman** [comment]
@B2o5T resolved conflicts again. Should I remove the changes to `action/index.js`? does that get automatically regenerated on release?

**Comment by TuvalSimha** [comment]
@nathanchapman  This is still relevant?

**Comment by nathanchapman** [comment]
Confirmed the fix, thanks @TuvalSimha!

**Comment by TuvalSimha** [comment]
@nathanchapman  Great news! thank you!

**Pull request closed without merging**
