### PR TITLE
GraphQL v16 support

### PR DESCRIPTION
**Pull request by ardatan**

### CODE REVIEW

**Comment by ardatan** [comment]
I removed Node 10 because v16 doesn't support it and it has been no longer maintained.

**Review by kamilkisiela — APPROVED** [review]
That's exactly how I would do it, perfect!

**Comment by sandromartis** [comment]
Can this be published to npm?

It seems that the latest version on npm has no GraphQL v16 support. It's currently blocking us from upgrading to 16.
Would be awesome if you could publish it :)

**Comment by kamilkisiela** [comment]
It's there since v3.1.0

**Comment by mshick** [comment]
@kamilkisiela Thanks — I think the issue is that [graphql-cli](https://github.com/Urigo/graphql-cli) installs old versions of the CLI plugins, e.g, [@graphql-cli/validate](https://www.npmjs.com/package/@graphql-cli/validate) which happen to link back to this repo.

I'm unclear on the history of these projects. Is there a preferred way to get the validation and other functionality from the `graphql-cli` subcommands that use more recent releases from this repo?

**Pull request merged**
