### PR TITLE
Fix ignored `approve-label` for `push` events

### LINKED ISSUE #1971: Expected Breaking Change label not working
**Describe the bug**

After adding the expected breaking change label the check is still failing on an open pr. During original implementation of the action in the repo I had tested this and it was working as expected. The only thing that has changed is after I merged the action we made it a required check on open PRs

**Expected behavior**
When a breaking change is introduced and the PR has the expected breaking change label on it the check should still pass.

**Environment:**
Github Action Implemented:
```yml
name: Schema Validation

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:schema.gql'
          approve-label: 'expected breaking change'
```

|Checks|Checks|Checks|
|---|---|--|
|Screen Shot 2021-07-09 at 1 34 20 PM|Screen Shot 2021-07-09 at 1 34 09 PM|Screen Shot 2021-07-09 at 1 44 28 PM|

### LINKED ISSUE #2091: approve-label is ignored with action v3.1.1
**Describe the bug**
[`approve-label`](https://www.graphql-inspector.com/docs/products/action#approve-label) is ignored with GitHub Action `kamilkisiela/graphql-inspector@v3.1.1` whether using the default `approved-breaking-change` or specifying a custom label.

**To Reproduce**

1. Add action to GitHub workflow:
```
- name: GraphQL Inspector
  uses: kamilkisiela/graphql-inspector@v3.1.1
  with:
      approve-label: 'approved-breaking-change'
      schema: 'master:path/to/schema.graphql'
```
2. Commit breaking change and open PR
3. Add `approved-breaking-change` label to PR
image

**Expected behavior**
`approve-label` is detected and workflow succeeds.

**Environment:**

- OS:
- `@graphql-inspector/...`: kamilkisiela/graphql-inspector@v3.1.1
- `graphql`: 16.3.0
- NodeJS: 12

**Additional context**
I tested with every version back to 2.5.0 and got the same result in each which makes me wonder if GitHub has changed something in their environment.

### PR DESCRIPTION
**Pull request by mgyarmathy**
## Description

The `approve-label` option in the graphql-inspector GitHub Action currently only works for [`pull_request`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) events. This is particularly confusing because [the docs](https://github.com/kamilkisiela/graphql-inspector/blob/master/website/docs/products/action.md?plain=1#L11-L32) nudge you towards using the [`push`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push) event trigger.

This PR updates the Github Action to support both kinds of event types by fetching Pull Request label information using the current commit SHA rather than retrieving it from the event payload (which is missing for [`push`](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push) events)

Fixes #2091, Fixes #1971

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Using the following GitHub Actions configuration:

```yml
name: CI
on:
  push:
    branches-ignore: [main]

jobs:
  graphql-inspector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kamilkisiela/graphql-inspector@3.2.0
        with:
          schema: 'main:graphql-schemas/coach-tools.graphql'
```

I created a PR introducing a breaking change to my GraphQL schema:

image

Then I added the default `approve-label` to the PR and re-ran CI:
image

The graphql-inspector job continued to fail:
image

Switched the action to use the `pgahq/graphql-inspector@2091-approve-label` fork. And re-ran the task. It now passes:

image

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

## Further comments

I think this issue could also be resolved by updating the GitHub Action docs to reference the `pull_request` `synchronize` event as the trigger instead of `push`. However, the solution I landed on satisfies both use-cases.

### CODE REVIEW

**Comment by mgyarmathy** [comment]
@kamilkisiela I don't have adequate permissions to add you as a reviewer to this PR, but I wanted to notify you that this is ready for you (or another team member) to review

**Comment by mybrainishuge** [comment]
Thanks @mgyarmathy for taking care of this!

@kamilkisiela, thanks for merging this. I see this wasn't included in the v3.2.0 release today. When is this fix scheduled to be published?

**Comment by mybrainishuge** [comment]
I changed the version of gql inspector from `master` back to `3.2.0`, merged, and the build succeeded. I changed it again from `3.2.0` to `master`, merged, and the build failed with the error referenced above. The builds for these PRs don't fail, the failure occurs only when merging into our `master` branch using the `master` version of gql inspector. This error may not be related to your changes, but it's definitely related to using the `master` version of gql inspector.

**Comment by marcusglowe** [comment]
I'm also running into this on a private repo, where we're getting `Error: result.repository.object.text is null` as of today.

Looks like this here: https://github.com/kamilkisiela/graphql-inspector/blob/7136ef4ba38a0b96062bf18b6c2d5b5ce3f137e5/packages/action/src/run.ts#L321

It's a little hard for me to follow the code (sorry, unfamiliar) but I think changing the definition of where pull request is coming from changed the code flow such that it's now requesting data from a branch that no longer exists. (github action probably ensured that `github.context.payload.pull_request` was not defined on this merge event, but searching for pull requests by that commit sha ensures those PRs are available)

One quick fix might be checking the PR is currently open if you want to keep using the octokit request

**Comment by mgyarmathy** [comment]
> I'm also running into this on a private repo, where we're getting `Error: result.repository.object.text is null` as of today.
> 
> Looks like this here:
> 
> https://github.com/kamilkisiela/graphql-inspector/blob/7136ef4ba38a0b96062bf18b6c2d5b5ce3f137e5/packages/action/src/run.ts#L321
> 
> It's a little hard for me to follow the code (sorry, unfamiliar) but I think changing the definition of where pull request is coming from changed the code flow such that it's now requesting data from a branch that no longer exists (we do delete on merge). The github action previous event probably ensured that `github.context.payload.pull_request` was not defined on this merge event, but searching for pull requests by that commit sha ensures those PRs returns data.
> 
> One quick fix might be checking the PR is currently open if you want to keep using the octokit request

Thanks for the feedback. I've forked the project and added the proposed fix to `pgahq/graphql-inspector@pr-2133-follow-up` (https://github.com/pgahq/graphql-inspector/commit/d52263dcadbd9ff6c3dcc8d0e3852c654b7406c5). Can you confirm this fix works before I open a follow-up PR?

**Comment by marcusglowe** [comment]
Thanks for the quick fix - Will test this tonight @mgyarmathy

**Comment by marcusglowe** [comment]
@mgyarmathy that fixed it! Thanks

**Comment by mgyarmathy** [comment]
> @mgyarmathy that fixed it! Thanks!

Wonderful. @kamilkisiela follow-up PR incoming

**Comment by jpduong** [comment]
having the same issue

```name: Schema validation

on:
  pull_request:
    types: [opened, synchronize, reopened]


permissions:
  actions: write
  checks: write
  contents: read 
  pull-requests: write 
  security-events: write

jobs:
  check-schema:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set target branch for schema comparison
        id: set_target_branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev-test' ]]; then
            echo "Using 'dev' as base branch for comparison."
            echo "::set-output name=target_branch::dev"
          else
            echo "Using 'main' as base branch for comparison."
            echo "::set-output name=target_branch::main"
          fi

      - name: Install GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          approve-label: 'approved-breaking-change'
          schema: ${{ steps.set_target_branch.outputs.target_branch }}:metadata/actions.graphql
```

image

image

**Pull request merged**
