### PR TITLE
feat: allow rules for diff command via graphql config

### PR DESCRIPTION
**Pull request by martyganz**
WIP. Need to add tests and actually test it with a config file

### CODE REVIEW

**Comment by ardatan** [comment]
Thanks @martyganz ! Is there anything we can help for this PR?

**Comment by TuvalSimha** [comment]
Hey @martyganz,

This PR is still relevant?

**Comment by TuvalSimha** [comment]
Hey @martyganz,
This PR is still relevant?

**Comment by TuvalSimha** [comment]
Hey @martyganz,
Just close this pull request, if this is still relevant, you are more than welcome to reopen it, update me and assign me to review :)
Thank you!

**Pull request closed without merging**
