### PR TITLE
coverage: provide overall statistics about coverage

### LINKED ISSUE #2183: coverage: provide statistics about coverage
Schema coverage command should provide statistics about the coverage:
* num of types in schema
* num of types covered
* num of types fully covered
* num of fields in schema (including arguments)
* num of fields covered (including arguments)
* percentage of types covered
* percentage of types fully covered
* percentage of fields covered

Statistics should be part of output JSON, and percentages should be also printed to console output.

I can contribute this feature as I wrote it already in my project.

### PR DESCRIPTION
**Pull request by velias**
## Description

Extension of the coverage module to provide overall statistics of the coverage. 
Console output contains info like percentage of "Types covered", "Types fully covered" and "Fields fully covered" (fields stat contains also arguments). 
JSON output contains more detailed output, like num of types, num of types covered, num of types fully covered, num of fields and num of fields covered (fields numbers contain also arguments).

Motivation is to have simple overall overview of the schema coverage. Also overall statistic number allows to create badge for source code repo of your project.

Fixes #2183

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

* `./packages/core/__tests__/coverage/coverage.ts` test has been extended to cover statistics.
* `./example` has been used to test coverage cli, example json oputput (`coverage.json`) is updated 

**Test Environment**:

- OS: ubuntu linux 22.04
- NodeJS: v16.17.1

## Checklist:

- [X] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by TuvalSimha** [comment]
Hey @velias :),

Thank you for the suggestion, I find it very useful!
Can you please add one more unit test and make sure the CI checks do not fail?

**Review by TuvalSimha — CHANGES_REQUESTED** [review]
- [ ]  Add `Changeset`
- [ ]  Add one more unit test
- [ ]  Make sure the CI checks pass

**Comment by velias** [comment]
@TuvalSimha thanks, for sure I'll do my best to provide correct PR. I'm only not sure what do you mean by "Add one more unit test"? Which test, what exactly should be tested?

**Comment by TuvalSimha** [comment]
> @TuvalSimha thanks, for sure I'll do my best to provide correct PR. I'm only not sure what do you mean by "Add one more unit test"? Which test, what exactly should be tested?

@velias Thank you!
Usually, we try to cover some edge cases for new features, this is not required, but if you have more unit test edge cases for that, it will be nice :)

**Comment by velias** [comment]
@TuvalSimha OK, I implemented there changes:

* rebased whole PR to latest master
* added `changeset`
* ran prettier so builds looks OK
* added one unit test to `core/coverage`. I was not able to find any tests for command.
* changed image with `coverage` command output for doc/website to show changed output 

Hope this makes PR mergeable

**Comment by velias** [comment]
@TuvalSimha I'm not sure why is `pr / algolia / algolia-records-check (pull_request) ` failing. I'm even not sure what is this check doing. Any idea/help?

**Comment by TuvalSimha** [comment]
> 



> @TuvalSimha I'm not sure why is `pr / algolia / algolia-records-check (pull_request) ` failing. I'm even not sure what is this check doing. Any idea/help? It may be related to coverage doc change, but there is not any reasonable error message sayin what is wrong, error is `Error: Resource not accessible by integration`

@velias  Hey :)
Not sure why, I guess because it’s a fork?

**Comment by velias** [comment]
@TuvalSimha OK, so does it mean my PR is OK ?

**Review by TuvalSimha — APPROVED** [review]

**Comment by TuvalSimha** [comment]
Hey @velias :)
Thank you very much! I found it very useful. Feel free to think about more statistics features for coverage and open new PRs.

**Comment by velias** [comment]
@TuvalSimha thanks for merging.
I don't know about more stats yet, but I thought about producing badge image from overall stats. We use it in our CI/CD in gitlab repo. It is relatively easy to produce once stats are in coverage results, but maybe commandline command should have option to generate it OOTB. But it requires some dependency, eg. [`badge-maker`](https://www.npmjs.com/package/badge-maker?activeTab=readme). So let me know if its addition looks beneficial and you find it acceptable.

**Comment by velias** [comment]
@TuvalSimha looks like `core` package was not released, so coverage command is broken now. Sorry, maybe I screwed changeset file (but I think I selected core during its creation). Any idea how to patch this?

**Pull request merged**
